# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/final_year
spring.datasource.username=postgres
spring.datasource.password=postgres1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET:auca_contract_system_super_secret_key_2026_very_long_string_for_security}
app.jwt.expiration=86400000

# AUCA IMS API
# AUCA IMS Integration Settings
auca.api.base-url=https://auca-ims.onrender.com
auca.api.key=52c55394b2b3b1ab2c6803543941be428801a14c079b63df87fb58d3e295976d

# Logging
logging.level.com.auca=DEBUG
logging.level.org.springframework.security=INFO

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Scheduler
spring.task.scheduling.enabled=true