# Server
server.port=${PORT:8080}

# Database
spring.datasource.url=jdbc:postgresql://dpg-d8eoj342m8qs73959ojg-a:5432/final_year_d9kb
spring.datasource.username=postgres1
spring.datasource.password=xFV5DA5YD6M0gYfxFxakNYUyiyA9EFrc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=auca_contract_system_super_secret_key_2026_very_long_string_for_security
app.jwt.expiration=86400000

# AUCA IMS API
auca.api.base-url=https://auca-ims.onrender.com
auca.api.key=YOUR_API_KEY_HERE

# Logging
logging.level.com.auca=DEBUG
logging.level.org.springframework.security=INFO

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Scheduler
spring.task.scheduling.enabled=true
